### PR TITLE
[APP] New web application created with react.js

### PR DESCRIPTION
**Pull request by leandro-xavier**
Is a very simple app create in react.js, using heroku as hosting.
This app contains pagination, search bar, songs components, video components and more.

Very soon I will update the app, to make it look better.

### CODE REVIEW

**Comment by Dazorn96** [comment]
@leandro-xavier could you update the description in english please?

**Comment by leandro-xavier** [comment]
@Dazorn96 perfect, 
I already changed the title.

**Comment by Dazorn96** [comment]
> @Dazorn96 perfect, I already changed the title.

Ok, waiting for your commit

**Comment by Dazorn96** [comment]
Closed for inactivity

**Pull request closed without merging**
